angular/package.json
react-vite/package.json
react/package.json

Bumped version of tegel to latest (0.0.4)

feat(tegel): bumped tegel version

---

react/src/App.tsx
react/src/components/ModeSwitcher.tsx
react/src/index.css

Minor setup fixes and imported accordion and banner.
**How to test** 
1. Checkout branch
2. Cd into the react folder
3. Run npm run start
4. Check the page and make sure light/dark mode works as expected.

feat(accordion & banner): integrated components

---

react/src/components/ModeSwitcher.tsx

Implemented correct use of event handler.

fix(toggle): correct event handler implementation

---

react/src/App.tsx

Imported the block component for the dark/light mode demo.

feat(block): integrated component

---

react/src/App.tsx

feat(mode): integrated checkbox

---

react/package-lock.json
react/src/App.tsx
react/src/index.css

1. Adding breadcrumb component
2. Small improvement for overflow and padding

feat(mode): integrating breadcrumb

---

react/src/App.tsx
react/src/index.css

1. Adding button component - a couple of variations
2. Make a mode switcher remain in the same place so we can easily switch modes even when we are at the bottom of the page.

feat(mode): integrating button component

---

react/src/App.tsx

Added the radio button component, both native and web component versions.

feat(mode): radio button component integration

---

react/src/App.tsx

feat:(mode): slider component integration

---

react/src/App.tsx
react/src/components/DataTable.tsx

Added data table components. Native/Web component. Wrapped them in a component to not bloat the App.tsx to much.

feat(mode): added data table components

---

react/src/App.tsx

feat(mode): datetime component integration

---

react/src/App.tsx

Added dropdown components, both native, web component (default and multiselect).

feat(mode): dropdown components integration

---

react/src/App.tsx

feat(mode): link components integration

---

react/src/App.tsx

feat(mode): message component integration

---

react-cra/src/components/Header.tsx

Use router link to allow for seamless routing. This also keeps the state of the mode selection across pages.
Use can read more here: https://reactrouter.com/en/main/components/link

feat(Link): use Router Link

---

.gitignore
react-cra/src/components/Header.tsx
react-cra/src/index.css

1. git ignore on a global level - has some IDE files to ignore
2. Make sure footer sticks to the bottom of the page no matter how long the page is AKA main to take all available height all the time

fix: main element to take all available height

---

react-cra/src/pages/NativeComponents.tsx
react-cra/src/pages/WebComponents.tsx

Added toggle for native and wc.

feat(mode): toggle components integration 

---

react-cra/src/index.css
react-cra/src/pages/WebComponents.tsx

feat(mode): tooltip components integration 

---

react-cra/src/pages/NativeComponents.tsx
react-cra/src/pages/WebComponents.tsx

feat(mode): modal components integration

---

react-cra/src/pages/WebComponents.tsx

Added spinner and removed duplicate popover.

feat(mode): spinner component integration

---

react-cra/src/index.css
react-cra/src/pages/NativeComponents.tsx
react-cra/src/pages/WebComponents.tsx

Adding missing native pairs of components.
I did commit per commit so you can easily follow up what was added or changed, please refer to it if possible.

feat(mode): adding native component pairs

---

react-cra/src/pages/WebComponents.tsx
react/src/pages/WebComponents.tsx

feat(mode):text field component integration

---

react-cra/src/pages/WebComponents.tsx

feat(mode): tabs components integration

---

react-cra/src/pages/WebComponents.tsx

Adding textarea component. Exists only as WebComponent.

feat(mode): adding textarea component

---

react-cra/src/pages/NativeComponents.tsx
react-cra/src/pages/WebComponents.tsx

Adding stepper component - both native and web

feat(mode): adding stepper component

---

react-cra/src/components/Footer.tsx

Added native footer to native components page

feat(mode): integrated footer

---

react-cra/src/pages/NativeComponents.tsx

Updated chips after new package release

fix(chips): updated the chips after new package release

---

react-cra/package-lock.json
react-cra/package.json
react-cra/src/components/Footer.tsx
react-cra/src/pages/WebComponents.tsx

Bumped version to latest (0.0.7) and updated the affected components.

bumped npm version and updated affected components

---

react-cra/package-lock.json
react-cra/package.json
react-cra/src/pages/WebComponents.tsx

- adding Tegel: 0.0.8 and quick testing it
- renaming sdds-badges --> sdds-badge
- renaming package of react test from demo to tegel-react-demo-cra

feat: tegel 0.0.8

---

src/App.tsx
src/components/TabsButtons.tsx
src/components/TabsLinks.tsx
src/components/TabsPanels.tsx
src/index.css
src/index.tsx
src/pages/TabsLinkPage.tsx
src/pages/TabsPage.tsx

- Added pages for tabs with buttons and links
- Added panels for tabs

test(tabs): integrated and added test cases for component

---

src/pages/FormPage.tsx

- Adding regular dropdown to the form page
- Demoing extraction of value from it

test(dropdown): integrated and added test case for a component

---

src/index.css
src/pages/FormPage.scss
src/pages/FormPage.tsx
src/utility-classes.css

Adding a spinner component to the form page.
It appears after clicking on submit button.

test(spinner): integrated and added test case for a component

---

src/App.tsx
src/index.tsx
src/pages/TextPage/TextPage.tsx
src/pages/TextPage/text-page.scss

- adding text page
- adding text, links and dividers on it to test it

feat(text-page): testing divider and link component case

---

src/pages/WebComponents.scss
src/pages/WebComponents.tsx

test(popover-menu): updating test case

---

src/pages/FormPage.tsx

As the title says...
PS: We would need to add linters and its rules to avoid lot of formatting in commits.

test(checkbox): adding checked and disabled to form test page

---

src/pages/FormPage.tsx
src/pages/norway-town.json
src/pages/sweden-town.json

- adding dropdown-v2 component
- conditionally set it to disabled in case Noway/Sweden is not the country of selection
- Norway town's dropdown has multi-select feature ON
- Sweden town's dropdown has filter feature ON

test(dropdown-v2): integrated and added test case for a component

---

src/components/PopOverCanvas.tsx
src/pages/WebComponents.tsx

feat: popover canvas testing

---

.prettierrc
.vscode/settings.json

Copy paste of the formatting rules within the tegel repository

chore: configure to format with prettier

---

src/App.tsx
src/components/Navigation/Header.scss
src/components/Navigation/Header.tsx
src/index.tsx
src/pages/NotificationPage.tsx
src/pages/SettingsPage.tsx

Added test for badge component.

feat(badge): manual testing

---

src/App.tsx
src/components/Navigation/SideMenu.tsx
src/index.css

Fixes: https://tegel.atlassian.net/browse/DTS-1964

fix/added link to table page and fixed position on side-menu

---

src/components/Navigation/Header.tsx
src/index.tsx
src/pages/ChipsPage/ChipsPage.tsx
src/pages/WebComponents.tsx

Function
Missing some props, created issue.
tdsChange events are fired. Can not be disabled currently.
Tested in form submit, validation does not seem to be needed for the use case of a chip?
Appearance
Wrong bg color, created issue DTS-2072
Both sm and lg sizes are 1px too tall vs Figma.
Outer padding on the side of an icon is `16px` in lg, and `12px` in sm. Should be `8px` in lg, and `6px` in sm. (Created issue DTS-2074)
Consistency
'type' prop is inconsistent with tds-button and tds-message. Created issue DTS-2066

feat(chips): testing

---

src/pages/FormPage.scss
src/pages/FormPage.tsx

Added test for the Tooltip component.

feat(tooltip): manual testing

---

package-lock.json
package.json
src/components/Navigation/Header.tsx
src/index.css
src/pages/FormPage.tsx
src/pages/WebComponents.tsx

Bumped @scania/tegel version to 0.0.10 and did minor clean-up to ensure environment can start.

chore: bump tegel version to 0.0.10

---

src/pages/FormPage.tsx

On the Form page try to set Norway as the country to see if the dropdown will be filled up with Norweigan towns.
Compare it with a main branch or Netlify like of the main branch.

fix(dropdown): assigning json for norway in separate if statement

---

src/pages/ChipsPage/ChipsPage.tsx

Update chip component so it reflect new slots

fix(chip): new slots

---

src/components/Navigation/Header.tsx

Fixes: https://tegel.atlassian.net/jira/software/projects/DTS/boards/1?selectedIssue=DTS-2136

fix(header): update slot name in header-dropdown

---

src/components/Navigation/Header.scss
src/components/Navigation/Header.tsx

Fixes: https://tegel.atlassian.net/jira/software/projects/DTS/boards/1?selectedIssue=DTS-2146

fix(header): update slot names for user menu in header-dropdown

---

src/components/Modal.tsx
src/components/Table/BatchActionTable.tsx
src/pages/NotificationPage.tsx

fix(modal): new slots

---

src/components/Table/BatchActionTable.tsx
src/components/Table/ExpandTable.tsx
src/components/Table/PaginationTable.tsx
src/components/Table/SearchTable.tsx
src/components/Table/SortableTable.tsx
src/components/Table/example-data.json

Fixing:
- slot names
- add/remove event listeners logic
- updating new and removed props
- changing logic for adding bodyData

fix(table): slot, bodyData, events improvements

---

package-lock.json

chore: lock file update

---

src/components/PopOverCanvas.tsx
src/index.css

- Updating popover-canvas content to reflect one in Storybook
- Removing duplicate of the rule in CSS

fix(popover-canvas): update component's content

---

src/index.css

Implemented a slimmed CSS-reset which doesn't break our components.

implmented CSS reset

---

src/components/PopOverCanvas.tsx

Tested that referenceEl works. 
Setting it directly on the tag with JSX does not work since non-react camelCase JSX properties will be lowercased and interpreted as attributes instead, should work when we have react wrappers though.
Using useEffect to set it imperatively worked though, as demonstrated here.

feat(popover-canvas): test referenceEl prop

---

src/components/Table/BasicTable.tsx
src/components/Table/BatchActionTable.tsx
src/components/Table/ExpandTable.tsx
src/components/Table/PaginationTable.tsx
src/components/Table/SearchTable.tsx
src/components/Table/SortableTable.tsx

Updated prop names in Tables to regain functionality.

fix(table): update prop names

---

src/components/Banner.tsx

Aligns with: https://github.com/scania-digital-design-system/tegel-angular-demo/pull/56
Fixes: https://tegel.atlassian.net/browse/CDEP-2469

fix: banner alignement

---

src/components/Block.tsx

Fixes: https://tegel.atlassian.net/browse/CDEP-2470

fix: block alignment

---

src/components/Link.tsx

Fixes: https://tegel.atlassian.net/browse/CDEP-2473

fix: link alignment

---

src/components/Modal/Modal.tsx
src/components/Modal/ModalExample.tsx

Aligns with: https://github.com/scania-digital-design-system/tegel-angular-demo/pull/58
Fixes: https://tegel.atlassian.net/browse/CDEP-2474 & https://tegel.atlassian.net/browse/CDEP-2476

fix: modal alignment

---

src/components/TextField.tsx
src/components/Textarea.tsx
src/pages/WebComponents/WebComponents.tsx

Fixes: https://tegel.atlassian.net/browse/CDEP-2482

fix: textarea/text-field alignment

---

src/MainLayout.tsx

Fixes: https://tegel.atlassian.net/browse/CDEP-2572

fix: background alignment

---

src/App.tsx

Aligns with: https://github.com/scania-digital-design-system/tegel-angular-demo/pull/68
Fixes: https://tegel.atlassian.net/browse/CDEP-2697

fix: user alignment

---

src/pages/FormPages/FormPage.tsx

Aligns with: https://github.com/scania-digital-design-system/tegel-angular-demo/pull/67
Fixes: https://tegel.atlassian.net/browse/CDEP-2576

fix: form-page alignment

---

src/components/Table/ExpandTable.tsx

Aligns with: https://github.com/scania-digital-design-system/tegel-angular-demo/pull/64
Fixes: https://tegel.atlassian.net/browse/CDEP-2580

fix: table alignment

---

src/components/Stepper/Stepper.tsx

Aligns with: https://github.com/scania-digital-design-system/tegel-angular-demo/pull/69
Fixes: https://tegel.atlassian.net/browse/CDEP-2704

fix: stepper alignment

---

src/MainLayout.tsx
src/index.css
src/reset.css

Fixes: https://tegel.atlassian.net/browse/CDEP-2472

fix: aligned scroll behaviour

---

src/components/Block.tsx
src/components/Modal/ModalExample.tsx
src/components/Navigation/AppBreadcrumbs/AppBreadcrumbs.scss
src/components/Navigation/AppBreadcrumbs/AppBreadcrumbs.tsx
src/index.css
src/pages/NotificationPage.tsx
src/pages/WebComponents/WebComponents.scss
src/pages/WebComponents/WebComponents.tsx

Fixes: https://tegel.atlassian.net/browse/CDEP-2477
Aligns with: https://github.com/scania-digital-design-system/tegel-angular-demo/pull/70

fix: spacing alignment

---

src/components/Footer.tsx
src/components/Tooltip.tsx

Fixes: https://tegel.atlassian.net/browse/CDEP-2747

fix: tooltip and footer

---

public/index.html

Enabling Plausible monitoring  for React Demo page.

feat: enable plausible monitoring

---

package-lock.json
package.json

Forgot to commit the version update

chore: update tegel version 1.1.0

---

package-lock.json
package.json

feat(tegel-react): using version 1.3.0

---

README.md

Fixes: https://tegel.atlassian.net/jira/software/projects/CDEP/boards/1?assignee=63ff6d6c314f5088138187f0&selectedIssue=CDEP-2898

chore: update readme with correct url

---

package-lock.json
package.json

Bumping the code to use Tegel version 1.4.0

feat(tegel-react): using version 1.4.0

---

package-lock.json
package.json
src/MainBanner.tsx

feat(tegel-react): using version 1.5.0

---

package-lock.json
package.json
src/components/Table/BasicTable.tsx
src/components/Table/BatchActionTable.tsx
src/components/Table/ExpandTable.tsx
src/components/Table/FilterTable.tsx
src/components/Table/PaginationTable.tsx
src/components/Table/SortableTable.tsx

- use tegel 1.7.0
- updating table component

feat: tegel 1.7.0

---

package-lock.json
package.json

feat: using tegel 1.8.0

---

package-lock.json
package.json

Bumping version after code release

feat: tegel 1.8.1.

---

package-lock.json
package.json

feat: tegel 1.8.2

---

package-lock.json
package.json

feat: tegel 1.9.1

---

package-lock.json
package.json

Update @scania/tegel-react version after release

feat: release 1.11.0

---

package-lock.json
package.json

Bumped tegel version to 1.12.0

feat: tegel 1.12.0

---

package-lock.json
package.json

feat: tegel@1.12.1

---

package-lock.json
package.json

feat: tegel 1.13.0

---

package-lock.json
package.json

feat: tegel 1.14.0

---

package-lock.json
package.json

release: bump version 1.17.0

---

package-lock.json
src/components/Table/PaginationTable.tsx
src/components/Table/ZebraTable.tsx
src/pages/TablePage.tsx

Added examples on: 
- table pagination with rows to display dropdown logic
- all examples on zebra mode

feat: table pagination and zebra examples

---

package-lock.json
package.json

Added new tegel version 1.19.0

feat: tegel@1.19.0

---

package-lock.json
package.json

feat: tegel@1.21.0

---

package-lock.json
package.json

release: tegel@1.21.1

---

package-lock.json
package.json

release: tegel@1.22.0

---

package-lock.json
package.json

Updated scania/tegel-react to version 1.23.0

release: version 1.23.0

---

package-lock.json
package.json

release: tegel@1.24.0

---

package-lock.json
package.json

release: version 1.25.0

---

package-lock.json
package.json

feat: tegel 1.34.0

---

package-lock.json
package.json

Update to new version of Tegel

feat: tegel 1.35.0

---

.github/CODEOWNERS

Removed mistermalm from codeowners file

chore(codeowners): removed mistermalm

---

src/components/Tag.tsx
src/pages/WebComponents/WebComponents.tsx

Introducing the tag component on the demo page
Navigate to the demo page and make sure it looks ok.

feat: tag component to demo page
